### PR TITLE
Compile on Ubuntu 17.10

### PR DESCRIPTION
**Pull request by at15**
- using fb version 2018.02.05.00
- seems thrift is having trouble
  - new version is using cmake and need to specify the folder for mstch ...
  - removed `thriftz` form FindThrift.cmake
- used `thrift1` to compile instead of the python compiler

````
pushd fbthrift-${FB_VERSION}/thrift
# autoreconf -ivf
# ./configure --prefix=/usr/local/facebook-${FB_VERSION}
cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/facebook-${FB_VERSION} -DMSTCH_INCLUDE_DIRS=/usr/local/facebook-${FB_VERSION}/include/mstch .
make install -j $(nproc)
popd
````

````
/usr/local/facebook/bin/thrift1 --templates /usr/local/facebook/include/thrift/templates --gen mstch_cpp2 -I ../.. "$THRIFT_FILE"
````

````
../../if/libberingei_thrift.a(beringei_data_types.cpp.o): In function
`apache::thrift::BinaryProtocolReader::readBool(bool&)':
beringei_data_types.cpp:(.text._ZN6apache6thrift20BinaryProtocolReader8readBoolERb[_ZN6apache6thrift20BinaryProtocolReader8readBoolERb]+0x30):
undefined reference to
`apache::thrift::protocol::TProtocolException::throwBoolValueOutOfRange(unsigned
char)'
../../if/libberingei_thrift.a(beringei_data_types.cpp.o): In function
`apache::thrift::BinaryProtocolReader::checkStringSize(int)':
beringei_data_types.cpp:(.text._ZN6apache6thrift20BinaryProtocolReader15checkStringSizeEi[_ZN6apache6thrift20BinaryProtocolReader15checkStringSizeEi]+0x16):
undefined reference to
`apache::thrift::protocol::TProtocolException::throwNegativeSize()'
beringei_data_types.cpp:(.text._ZN6apache6thrift20BinaryProtocolReader15checkStringSizeEi[_ZN6apache6thrift20BinaryProtocolReader15checkStringSizeEi]+0x30):
undefined reference to
`apache::thrift::protocol::TProtocolException::throwExceededSizeLimit()'
../../if/libberingei_thrift.a(beringei_data_types.cpp.o): In function
`apache::thrift::BinaryProtocolReader::checkContainerSize(int)':
beringei_data_types.cpp:(.text._ZN6apache6thrift20BinaryProtocolReader18checkContainerSizeEi[_ZN6apache6thrift20BinaryProtocolReader18checkContainerSizeEi]+0x16):
undefined reference to
`apache::thrift::protocol::TProtocolException::throwNegativeSize()'
beringei_data_types.cpp:(.text._ZN6apache6thrift20BinaryProtocolReader18checkContainerSizeEi[_ZN6apache6thrift20BinaryProtocolReader18checkContainerSizeEi]+0x32):
undefined reference to
`apache::thrift::protocol::TProtocolException::throwExceededSizeLimit()'
../../if/libberingei_thrift.a(beringei_data_types.cpp.o): In function
`apache::thrift::CompactProtocolReader::readMapBegin(apache::thrift::protocol::TType&,
apache::thrift::protocol::TType&, unsigned int&)':
beringei_data_types.cpp:(.text._ZN6apache6thrift21CompactProtocolReader12readMapBeginERNS0_8protocol5TTypeES4_Rj[_ZN6apache6thrift21CompactProtocolReader12readMapBeginERNS0_8protocol5TTypeES4_Rj]+0x6b):
undefined reference to
`apache::thrift::protocol::TProtocolException::throwNegativeSize()'
beringei_data_types.cpp:(.text._ZN6apache6thrift21CompactProtocolReader12readMapBeginERNS0_8protocol5TTypeES4_Rj[_ZN6apache6thrift21CompactProtocolReader12readMapBeginERNS0_8protocol5TTypeES4_Rj]+0x89):
undefined reference to
`apache::thrift::protocol::TProtocolException::throwExceededSizeLimit()'
../../if/libberingei_thrift.a(beringei_data_types.cpp.o): In function
`apache::thrift::CompactProtocolReader::readListBegin(apache::thrift::protocol::TType&,
unsigned int&)':
beringei_data_types.cpp:(.text._ZN6apache6thrift21CompactProtocolReader13readListBeginERNS0_8protocol5TTypeERj[_ZN6apache6thrift21CompactProtocolReader13readListBeginERNS0_8protocol5TTypeERj]+0x6a):
undefined reference to
`apache::thrift::protocol::TProtocolException::throwNegativeSize()'
beringei_data_types.cpp:(.text._ZN6apache6thrift21CompactProtocolReader13readListBeginERNS0_8protocol5TTypeERj[_ZN6apache6thrift21CompactProtocolReader13readListBeginERNS0_8protocol5TTypeERj]+0x88):
undefined reference to
`apache::thrift::protocol::TProtocolException::throwExceededSizeLimit()'
../../if/libberingei_thrift.a(beringei_data_types.cpp.o): In function
`apache::thrift::CompactProtocolReader::readStringSize(int&)':
beringei_data_types.cpp:(.text._ZN6apache6thrift21CompactProtocolReader14readStringSizeERi[_ZN6apache6thrift21CompactProtocolReader14readStringSizeERi]+0x32):
undefined reference to
`apache::thrift::protocol::TProtocolException::throwNegativeSize()'
beringei_data_types.cpp:(.text._ZN6apache6thrift21CompactProtocolReader14readStringSizeERi[_ZN6apache6thrift21CompactProtocolReader14readStringSizeERi]+0x51):
undefined reference to
`apache::thrift::protocol::TProtocolException::throwExceededSizeLimit()'
../../if/libberingei_thrift.a(beringei_data_types.cpp.o): In function
`void
apache::thrift::BinaryProtocolReader::readStringBody<std::__cxx11::basic_string<char,
std::char_traits<char>, std::allocator<char> >
>(std::__cxx11::basic_string<char, std::char_traits<char>,
std::allocator<char> >&, int)':
beringei_data_types.cpp:(.text._ZN6apache6thrift20BinaryProtocolReader14readStringBodyINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRT_i[_ZN6apache6thrift20BinaryProtocolReader14readStringBodyINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRT_i]+0xd4):
undefined reference to
`apache::thrift::protocol::TProtocolException::throwExceededSizeLimit()'
../../if/libberingei_thrift.a(beringei_data_types.cpp.o): In function
`void apache::thrift::util::detail::readVarintMediumSlow<int,
folly::io::Cursor, false>(folly::io::Cursor&, int&, unsigned char
const*, unsigned long)':
beringei_data_types.cpp:(.text._ZN6apache6thrift4util6detail20readVarintMediumSlowIiN5folly2io6CursorELb0EEEvRT0_RT_PKhm[_ZN6apache6thrift4util6detail20readVarintMediumSlowIiN5folly2io6CursorELb0EEEvRT0_RT_PKhm]+0x18e):
undefined reference to
`apache::thrift::util::detail::throwInvalidVarint()'
../../if/libberingei_thrift.a(beringei_data_types.cpp.o): In function
`void
apache::thrift::CompactProtocolReader::readStringBody<std::__cxx11::basic_string<char,
std::char_traits<char>, std::allocator<char> >
>(std::__cxx11::basic_string<char, std::char_traits<char>,
std::allocator<char> >&, int)':
beringei_data_types.cpp:(.text._ZN6apache6thrift21CompactProtocolReader14readStringBodyINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRT_i[_ZN6apache6thrift21CompactProtocolReader14readStringBodyINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRT_i]+0xac):
undefined reference to
`apache::thrift::protocol::TProtocolException::throwExceededSizeLimit()'
../../if/libberingei_thrift.a(beringei_data_types.cpp.o): In function
`void apache::thrift::util::detail::readVarintMediumSlow<unsigned long,
folly::io::Cursor, false>(folly::io::Cursor&, unsigned long&, unsigned
char const*, unsigned long)':
beringei_data_types.cpp:(.text._ZN6apache6thrift4util6detail20readVarintMediumSlowImN5folly2io6CursorELb0EEEvRT0_RT_PKhm[_ZN6apache6thrift4util6detail20readVarintMediumSlowImN5folly2io6CursorELb0EEEvRT0_RT_PKhm]+0x2d2):
undefined reference to
`apache::thrift::util::detail::throwInvalidVarint()'
../../if/libberingei_thrift.a(beringei_data_types.cpp.o): In function
`void
apache::thrift::detail::pm::protocol_methods<apache::thrift::type_class::list<apache::thrift::type_class::structure>,
std::vector<facebook::gorilla::TimeSeriesBlock,
std::allocator<facebook::gorilla::TimeSeriesBlock> >,
void>::read<apache::thrift::BinaryProtocolReader>(apache::thrift::BinaryProtocolReader&,
std::vector<facebook::gorilla::TimeSeriesBlock,
std::allocator<facebook::gorilla::TimeSeriesBlock> >&)':
beringei_data_types.cpp:(.text._ZN6apache6thrift6detail2pm16protocol_methodsINS0_10type_class4listINS4_9structureEEESt6vectorIN8facebook7gorilla15TimeSeriesBlockESaISB_EEvE4readINS0_20BinaryProtocolReaderEEEvRT_RSD_[_ZN6apache6thrift6detail2pm16protocol_methodsINS0_10type_class4listINS4_9structureEEESt6vectorIN8facebook7gorilla15TimeSeriesBlockESaISB_EEvE4readINS0_20BinaryProtocolReaderEEEvRT_RSD_]+0x5b):
undefined reference to
`apache::thrift::protocol::TProtocolException::throwReportedTypeMismatch()'
beringei_data_types.cpp:(.text._ZN6apache6thrift6detail2pm16protocol_methodsINS0_10type_class4listINS4_9structureEEESt6vectorIN8facebook7gorilla15TimeSeriesBlockESaISB_EEvE4readINS0_20BinaryProtocolReaderEEEvRT_RSD_[_ZN6apache6thrift6detail2pm16protocol_methodsINS0_10type_class4listINS4_9structureEEESt6vectorIN8facebook7gorilla15TimeSeriesBlockESaISB_EEvE4readINS0_20BinaryProtocolReaderEEEvRT_RSD_]+0xc4):
undefined reference to
`apache::thrift::protocol::TProtocolException::throwReportedTypeMismatch()'
../../if/libberingei_thrift.a(beringei_data_types.cpp.o): In function
`void
apache::thrift::detail::pm::protocol_methods<apache::thrift::type_class::list<apache::thrift::type_class::structure>,
std::vector<facebook::gorilla::TimeSeriesBlock,
std::allocator<facebook::gorilla::TimeSeriesBlock> >,
void>::read<apache::thrift::CompactProtocolReader>(apache::thrift::CompactProtocolReader&,
std::vector<facebook::gorilla::TimeSeriesBlock,
std::allocator<facebook::gorilla::TimeSeriesBlock> >&)':
beringei_data_types.cpp:(.text._ZN6apache6thrift6detail2pm16protocol_methodsINS0_10type_class4listINS4_9structureEEESt6vectorIN8facebook7gorilla15TimeSeriesBlockESaISB_EEvE4readINS0_21CompactProtocolReaderEEEvRT_RSD_[_ZN6apache6thrift6detail2pm16protocol_methodsINS0_10type_class4listINS4_9structureEEESt6vectorIN8facebook7gorilla15TimeSeriesBlockESaISB_EEvE4readINS0_21CompactProtocolReaderEEEvRT_RSD_]+0x5b):
undefined reference to
`apache::thrift::protocol::TProtocolException::throwReportedTypeMismatch()'
beringei_data_types.cpp:(.text._ZN6apache6thrift6detail2pm16protocol_methodsINS0_10type_class4listINS4_9structureEEESt6vectorIN8facebook7gorilla15TimeSeriesBlockESaISB_EEvE4readINS0_21CompactProtocolReaderEEEvRT_RSD_[_ZN6apache6thrift6detail2pm16protocol_methodsINS0_10type_class4listINS4_9structureEEESt6vectorIN8facebook7gorilla15TimeSeriesBlockESaISB_EEvE4readINS0_21CompactProtocolReaderEEEvRT_RSD_]+0xc4):
undefined reference to
`apache::thrift::protocol::TProtocolException::throwReportedTypeMismatch()'
../../if/libberingei_thrift.a(beringei_data_types.cpp.o): In function
`void
apache::thrift::detail::pm::protocol_methods<apache::thrift::type_class::list<apache::thrift::type_class::structure>,
std::vector<facebook::gorilla::Key,
std::allocator<facebook::gorilla::Key> >,
void>::read<apache::thrift::BinaryProtocolReader>(apache::thrift::BinaryProtocolReader&,
std::vector<facebook::gorilla::Key,
std::allocator<facebook::gorilla::Key> >&)':
beringei_data_types.cpp:(.text._ZN6apache6thrift6detail2pm16protocol_methodsINS0_10type_class4listINS4_9structureEEESt6vectorIN8facebook7gorilla3KeyESaISB_EEvE4readINS0_20BinaryProtocolReaderEEEvRT_RSD_[_ZN6apache6thrift6detail2pm16protocol_methodsINS0_10type_class4listINS4_9structureEEESt6vectorIN8facebook7gorilla3KeyESaISB_EEvE4readINS0_20BinaryProtocolReaderEEEvRT_RSD_]+0x5b):
undefined reference to
`apache::thrift::protocol::TProtocolException::throwReportedTypeMismatch()'
../../if/libberingei_thrift.a(beringei_data_types.cpp.o):beringei_data_types.cpp:(.text._ZN6apache6thrift6detail2pm16protocol_methodsINS0_10type_class4listINS4_9structureEEESt6vectorIN8facebook7gorilla3KeyESaISB_EEvE4readINS0_20BinaryProtocolReaderEEEvRT_RSD_[_ZN6apache6thrift6detail2pm16protocol_methodsINS0_10type_class4listINS4_9structureEEESt6vectorIN8facebook7gorilla3KeyESaISB_EEvE4readINS0_20BinaryProtocolReaderEEEvRT_RSD_]+0xc4):
more undefined references to
`apache::thrift::protocol::TProtocolException::throwReportedTypeMismatch()'
follow
collect2: error: ld returned 1 exit status
beringei/lib/tests/CMakeFiles/beringei_core_test_bin.dir/build.make:424:
recipe for target 'beringei/lib/tests/beringei_core_test_bin' failed
make[2]: *** [beringei/lib/tests/beringei_core_test_bin] Error 1
CMakeFiles/Makefile2:332: recipe for target
'beringei/lib/tests/CMakeFiles/beringei_core_test_bin.dir/all' failed
make[1]: ***
[beringei/lib/tests/CMakeFiles/beringei_core_test_bin.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
````

### CODE REVIEW

**Comment by at15** [comment]
https://latedev.wordpress.com/2014/04/22/common-c-error-messages-2-unresolved-reference/ it seems fbthrift is not built properly? ....
